In [58]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import networkx as 
csv_data = pd.read_csv("acci.csv",engine = 'python')
csv_data

         구분   음주   무면허  통고처분     무인    범법  보행자  질서요청서
0   전북지방경찰청     0    1     0      0     0    0      0
1      전주완산  1146  172  3770  59455  4258  152     36
2      전주덕진   737  137  4731  42024  6629    1     27
3        군산   762  248  4632  59088  3497   54     64
4        익산   593  169  2105  49620  2240    1     34
5        정읍   172   79   518  16187   698    1      8
6        남원   155   60   660  18963  1449    0     20
7        김제   242  114  3286  21095   558    0     23
8        완주   172   79  1193  51503  1325    0     30
9        고창   100   46   336   9677   270    0      7
10       부안   101   29   261   7557   298    0      5
11       임실    27    7   113   8477   137    0     13
12       순창    40   17   198   3671   155    0      4
13       진안    31   16   112  21433   156    0     34
14       장수    31   12    47   5953   115    0     11
15       무주    41   15   167   6855   119    0      6
16     ９지구대   307   75  5976  52622     0    0     14
17    12지구대   110   28  6741  23929     0    0      6

In [65]:
group_names = ['작다','보통','크다']
csv_data['사고 빈도수'],mybin = pd.cut(csv_data['무인'],3,labels=group_names,retbins=True)
csv_data

         구분   음주   무면허  통고처분     무인    범법  보행자  질서요청서   P 사고 빈도수
0   전북지방경찰청     0    1     0      0     0    0      0  작다     작다
1      전주완산  1146  172  3770  59455  4258  152     36  크다     크다
2      전주덕진   737  137  4731  42024  6629    1     27  크다     크다
3        군산   762  248  4632  59088  3497   54     64  크다     크다
4        익산   593  169  2105  49620  2240    1     34  크다     크다
5        정읍   172   79   518  16187   698    1      8  작다     작다
6        남원   155   60   660  18963  1449    0     20  작다     작다
7        김제   242  114  3286  21095   558    0     23  보통     보통
8        완주   172   79  1193  51503  1325    0     30  크다     크다
9        고창   100   46   336   9677   270    0      7  작다     작다
10       부안   101   29   261   7557   298    0      5  작다     작다
11       임실    27    7   113   8477   137    0     13  작다     작다
12       순창    40   17   198   3671   155    0      4  작다     작다
13       진안    31   16   112  21433   156    0     34  보통     보통
14       장수    31   12    47   5953   115    0     11  작다     작다
15       무주    41   15   167   6855   119    0      6  작다     작다
16     ９지구대   307   75  5976  52622     0    0     14  크다     크다
17    12지구대   110   28  6741  23929     0    0      6  보통     보통

In [67]:
csv_data = pd.concat([csv_data, pd.get_dummies(csv_data['사고 빈도수'])],axis=1,sort=False)
csv_data

,구분,음주,무면허,통고처분,무인,범법,보행자,질서요청서,P,사고 빈도수,작다,보통,크다,작다,보통,크다
0,전북지방경찰청,0,1,0,0,0,0,0,작다,작다,1,0,0,1,0,0
1,전주완산,1146,172,3770,59455,4258,152,36,크다,크다,0,0,1,0,0,1
2,전주덕진,737,137,4731,42024,6629,1,27,크다,크다,0,0,1,0,0,1
3,군산,762,248,4632,59088,3497,54,64,크다,크다,0,0,1,0,0,1
4,익산,593,169,2105,49620,2240,1,34,크다,크다,0,0,1,0,0,1
5,정읍,172,79,518,16187,698,1,8,작다,작다,1,0,0,1,0,0
6,남원,155,60,660,18963,1449,0,20,작다,작다,1,0,0,1,0,0
7,김제,242,114,3286,21095,558,0,23,보통,보통,0,1,0,0,1,0
8,완주,172,79,1193,51503,1325,0,30,크다,크다,0,0,1,0,0,1
9,고창,100,46,336,9677,270,0,7,작다,작다,1,0,0,1,0,0
10,부안,101,29,261,7557,298,0,5,작다,작다,1,0,0,1,0,0
11,임실,27,7,113,8477,137,0,13,작다,작다,1,0,0,1,0,0
12,순창,40,17,198,3671,155,0,4,작다,작다,1,0,0,1,0,0
13,진안,31,16,112,21433,156,0,34,보통,보통,0,1,0,0,1,0
14,장수,31,12,47,5953,115,0,11,작다,작다,1,0,0,1,0,0
15,무주,41,15,167,6855,119,0,6,작다,작다,1,0,0,1,0,0
16,９지구대,307,75,5976,52622,0,0,14,크다,크다,0,0,1,0,0,1
17,12지구대,110,28,6741,23929,0,0,6,보통,보통,0,1,0,0,1,0

In [69]:
csv_data.isnull().sum()

구분        0
음주        0
무면허       0
통고처분      0
무인        0
범법        0
보행자       0
질서요청서     0
P         0
사고 빈도수    0
작다        0
보통        0
크다        0
작다        0
보통        0
크다        0
dtype: int64

In [71]:
csv_data['사고 빈도수'] = (csv_data['사고 빈도수']-csv_data['사고 빈도수'].min())/(csv_data['P'].max()- csv_data['P'].min())
csv_data

TypeError: unsupported operand type(s) for -: 'Categorical' and 'str'